habilidades = {
    'Ambidestro': 'Você é capaz de conseguir utilizar os dois lados do seu corpo com proficiência. Se possível, você pode portar dois itens ao mesmo tempo e utilizá-los normalmente como bem entender.',
    'Acadêmico': 'Após se esforçar em algo que você não é um bom usuário ainda, você pode ter vantagem nessa coisa e +1 no dado temporariamente. Para se esforçar você pode: estudar, aprender com alguém, tentar instintivamente, copiar etc (teste depende do que você quer aprender). Você não tem penalidade em natureza, história, artes e buscar.',
    'Ágil': 'Você ganha quatro pontos para distribuir em ações de Destreza. Ganha vantagem em Destreza. Pode escolher ser o primeiro a atacar. Sem penalidade em Escalar.',
    'Atento': 'Vantagem em testes e ações de Percepção. Mais 2 em Percepção. Você identifica truques (mágicas, ilusões etc). Sem penalidade em buscar.',
    'Atual': 'Ganha +2 na perícia Técnica e +1 em todas as ações de Técnica. Sem penalidade em Montar, buscar e Hacker e distribui entre elas quatro vantagens.',
    'Bruto': 'Você escolhe entre vantagem e +3 em Agarrar ou Derrubar; o não escolhido terá -1. Se tirar bom em Luta, você pode girar dois dados de dano e ficar com o melhor resultado. Sem penalidade em escalar.',
    'Concentrado': 'Se você conseguir passar uma rodada se concentrando, você roda 1d10, o dado que cair é a quantia de rodadas que você ganha uma vantagem em ações que sirvam para a situação e +2 em qualquer dado dentro dessas rodadas. Só pode ser usado uma vez por sessão e após usar, fica exausto por um turno.',
    'Corajoso': 'Você pode não ter debuff em certas situações que precisam de coragem. Você ganha vantagem em testes e +10 em Saúde Mental.',
    'Detetive': 'Ganha vantagem e +2 em Intelecto. +1 em Intuição e Investigar e só fracassa se tirar desastre. Sem penalidade em história, artes e buscar.',
    'Domador de Feras': 'Sempre terá sucesso em Acalmar. Qualquer "animal feroz" que esteja em sua presença, dependendo do que faça, ele pode não atacar. Você tem maestria em domar animais. Você pode entender o que os animais expressam com um teste de Intelecto. Sem penalidade em Natureza e Ilusão.',
    'Furtivo': 'Ganha +3 e vantagem em Furtividade. Sem penalidade em ilusão.',
    'Gênio': 'Buff de +2 em Sabedoria, +4 em Intelecto e vantagem em testes de Intelecto e suas ações. Sem penalidade em Natureza, História e Drogas ou Artes.',
    'Grande': 'Você ganha +5 pontos na sua bolsa, +5 PV e +1 em tamanho. Desvantagem em testes de Furtividade e Destreza.',
    'Imune': 'O seu corpo é totalmente imune de forma interna e externa. Você tem menor chance de entrar em um dos ⁠estados. Não leva danos massivos. O estado de morrendo dura 4 rodadas.',
    'Mágico': 'És um grande ilusionista. Sempre terá sucesso, vantagem e +3 em Ilusão. +2 e vantagem em Artes. +5 pontos de SM. Sem penalidade em Ilusão e Artes.',
    'Mano a Mano': 'Com essa habilidade, você ganha vantagem em qualquer ação de combate em lutas. +1 de dano em golpes físicos.',
    'Maromba': 'Ganha +1 de Força e +3 de dano físico ou +2 em Força e +1 de dano físico. Sem penalidade em Escalar.',
    'Médico': 'Os três primeiros kit médicos que você carregar contam como só um. O kit médico pode recuperar 2d10+6 PV invés de 2d8+2. Vantagem em ações médicas. Sem penalidade em Medicina e Drogas.',
    'Mentalista': 'Você consegue ter sempre sucesso em testes de Lábia ou Persuasão ou Mentir (você deve escolher um). Vantagem em Persuasão e Mentir. Você escolhe entre: + 1 em Lábia ou +3 em Persuadir. Sem penalidade em Ilusão e Artes.',
    'Metralhador': 'Você pode portar um rifle avançado. Com rifles, se mirar gastando um turno, você pode dar dois tiros, o primeiro com vantagem e o segundo normal. +4 de dano com rifles. Sem penalidade em Atirar.',
    'Piloto': 'Você sempre terá sucesso e vantagem em testes de dirigir em dois veículos de sua escolha. Nos outros, só a vantagem. +2 em dirigir. Sem penalidade em dirigir.',
    'Pistoleiro': 'Vantagem em Mirar e Atirar com pistolas (revólver). Pode dar dois tiros: sem mirar: ambos são dados normais. Mirando e atirando no mesmo turno: ambos tem uma vantagem. Mirando por um turno: o primeiro tiro será sucesso e o segundo terá uma vantagem. Sem penalidade em Atirar.',
    'Poderoso': 'Você é uma pessoa relativamente poderosa; você tem +2 de Poder, +1d10 SM e pode ter uma especialidade de classe a mais. Você não tem penalidades.',
    'Psicólogo': 'Ganha +3 na perícia de Psicologia; vantagem em todas suas ações e distribuir 4 pontos entre as ações de Psicologia.',
    'Rápido': 'Você é rápido e aproveita o seu tempo. Em batalhas você pode usar uma ação bônus ou principal a mais. Sem penalidade em Escalar. +1 em correr.',
    'Resistente': 'Você tem uma "armadura natural" que diminui dois em quaisquer dano. Você ganha +1d20 PV, não leva dano massivo e pode não sofrer de certos debuffs.',
    'Rico': 'Você pode adicionar no seu dinheiro mais R$3500. Sem penalidade em História.',
    'Sentido Apurado': 'Você tem os cinco sentidos apurados e resistentes. Vantagem em testes que utilizem destes sentidos (tem que haver a narração). Ter todos sentidos apurados pode ser um pouco ruim...',
    'Sniper': 'Usando uma sniper, ganha +2 em Mirar. Você pode portar uma sniper média. Mirar gastando um turno, +3 de dano com acerto normal; +6 em bom e +9 em extremo. Sem penalidade em Atirar.',
    'Simplório': 'Você, por ser simples, pode escolher entre duas coisas: aumentar a Sorte em +4. Ou jogar 3d20 e pegar o melhor resultado para substituir a sua sorte atual. Além disso, ganha dois pontos para distribuir nas perícias. Sem penalidades em Artes e buscar.',
    'Usuário de Espada': 'Com armas cortantes, você escolhe entre: +2 de dano ou vantagem em Cortar. +2 na ação Cortar.',
}